export const PME_CURRENT_OPERATION_WHATSAPP_SEEDS = [
  {
    id: 'wpp-lf-f1-003',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'leve',
    title: 'Lista fria — abertura sem pressão',
    body: 'Oi, {{nome_lead}}, tudo bem? Sou {{nome_corretor}}, da {{empresa}}. Tenho algumas opções de imóveis que podem fazer sentido na região. Posso te mandar algo bem objetivo por aqui?',
  },
  {
    id: 'wpp-lf-f1-004',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'consultivo',
    title: 'Lista fria — pergunta de momento',
    body: 'Olá, {{nome_lead}}. Tudo bem? Estou fazendo um contato rápido para entender se compra de imóvel ainda é um assunto para você neste momento ou se prefere que eu não siga por aqui.',
  },
  {
    id: 'wpp-lf-f1-005',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'direto',
    title: 'Lista fria — validação objetiva',
    body: '{{nome_lead}}, tudo bem? Aqui é {{nome_corretor}}, da {{empresa}}. Você ainda avalia imóvel em São Paulo ou esse assunto não está mais nos seus planos?',
  },
  {
    id: 'wpp-lf-f1-006',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'executivo',
    title: 'Lista fria — abordagem profissional',
    body: 'Olá, {{nome_lead}}. Sou {{nome_corretor}}, da {{empresa}}. Trabalho com oportunidades imobiliárias e gostaria de saber se faz sentido te apresentar opções dentro do seu perfil.',
  },
  {
    id: 'wpp-lf-f1-007',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'leve',
    title: 'Lista fria — posso enviar?',
    body: 'Oi, {{nome_lead}}. Tudo bem? Tenho algumas informações sobre imóveis que podem ser interessantes para quem olha a região de {{bairro}}. Posso te enviar uma opção para você avaliar sem compromisso?',
  },
  {
    id: 'wpp-lf-f1-008',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'consultivo',
    title: 'Lista fria — sem envio aleatório',
    body: 'Olá, {{nome_lead}}, tudo bem? Antes de te mandar qualquer material, queria confirmar se você tem interesse em receber opções de imóveis ou prefere que eu encerre o contato.',
  },
  {
    id: 'wpp-lf-f1-009',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'reativacao',
    title: 'Lista fria — interesse antigo',
    body: 'Oi, {{nome_lead}}. Aqui é {{nome_corretor}}, da {{empresa}}. Estou atualizando alguns contatos de pessoas que já avaliaram imóveis em algum momento. Ainda faz sentido falar sobre isso com você?',
  },
  {
    id: 'wpp-lf-f1-010',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'primeira_mensagem',
    tone: 'leve',
    title: 'Lista fria — escolha simples',
    body: '{{nome_lead}}, tudo bem? Posso te fazer uma pergunta rápida? Você está procurando imóvel hoje, quer apenas acompanhar oportunidades ou prefere não receber contato sobre isso?',
  },
  {
    id: 'wpp-lf-f2-002',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'leve',
    title: 'Lista fria — retomada com saída',
    body: 'Oi, {{nome_lead}}. Só retomando meu contato anterior. Se não for um bom momento para falar sobre imóvel, tudo bem. Se fizer sentido, te mando uma opção objetiva.',
  },
  {
    id: 'wpp-lf-f2-003',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'consultivo',
    title: 'Lista fria — confirmar perfil',
    body: '{{nome_lead}}, para eu não te mandar coisa fora do seu momento: você ainda avalia imóvel para morar, investir ou prefere não receber esse tipo de contato?',
  },
  {
    id: 'wpp-lf-f2-004',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'direto',
    title: 'Lista fria — resposta rápida',
    body: 'Olá, {{nome_lead}}. Posso te enviar uma opção de imóvel na região ou melhor eu encerrar esse contato por aqui? Uma resposta rápida já me ajuda.',
  },
  {
    id: 'wpp-lf-f2-005',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'leve',
    title: 'Lista fria — tentativa humana',
    body: '{{nome_lead}}, passando de novo por aqui porque talvez minha mensagem tenha se perdido. Você está em fase de procurar imóvel ou não é um assunto para agora?',
  },
  {
    id: 'wpp-lf-f2-006',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'executivo',
    title: 'Lista fria — abordagem discreta',
    body: 'Olá, {{nome_lead}}. Retomo de forma breve: caso esteja avaliando imóvel, posso te apresentar opções com mais critério. Se não fizer sentido, não sigo insistindo.',
  },
  {
    id: 'wpp-lf-f2-007',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'consultivo',
    title: 'Lista fria — região ou perfil',
    body: '{{nome_lead}}, você teria interesse em receber opções por região, valor aproximado ou perfil de planta? Se não estiver buscando, também posso pausar por aqui.',
  },
  {
    id: 'wpp-lf-f2-008',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'leve',
    title: 'Lista fria — sem compromisso',
    body: 'Oi, {{nome_lead}}. Posso te mandar uma única opção para você ver se faz sentido? Se não tiver aderência, eu não sigo te acionando.',
  },
  {
    id: 'wpp-lf-f2-009',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'direto',
    title: 'Lista fria — triagem honesta',
    body: '{{nome_lead}}, só para eu classificar corretamente por aqui: você quer receber opções de imóveis, prefere falar depois ou não tem interesse?',
  },
  {
    id: 'wpp-lf-f2-010',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'segunda_mensagem',
    tone: 'reativacao',
    title: 'Lista fria — reabrir conversa',
    body: 'Olá, {{nome_lead}}. Estou organizando meus retornos e queria confirmar se ainda posso te manter na lista de interessados em imóveis ou se retiro seu contato desta abordagem.',
  },
  {
    id: 'wpp-lf-f3-002',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'direto',
    title: 'Lista fria — decisão simples',
    body: '{{nome_lead}}, para eu não insistir sem necessidade: posso te enviar uma última opção de imóvel ou prefere que eu não fale mais sobre esse assunto?',
  },
  {
    id: 'wpp-lf-f3-003',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'consultivo',
    title: 'Lista fria — último filtro',
    body: 'Oi, {{nome_lead}}. Antes de pausar meu contato, queria confirmar: existe algum perfil de imóvel que faria sentido para você avaliar hoje?',
  },
  {
    id: 'wpp-lf-f3-004',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'urgencia_elegante',
    title: 'Lista fria — janela de oportunidade suave',
    body: '{{nome_lead}}, surgiram algumas opções que podem interessar quem acompanha imóveis na região. Quer receber uma seleção curta ou prefere que eu encerre?',
  },
  {
    id: 'wpp-lf-f3-005',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'leve',
    title: 'Lista fria — não quero incomodar',
    body: 'Olá, {{nome_lead}}. Não quero te incomodar. Só preciso saber se imóvel ainda é um tema aberto para você ou se posso pausar este contato.',
  },
  {
    id: 'wpp-lf-f3-006',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'executivo',
    title: 'Lista fria — contato final profissional',
    body: '{{nome_lead}}, faço este último contato de forma objetiva. Caso tenha interesse em avaliar imóveis com critério, eu posso te ajudar. Caso contrário, encerro por aqui.',
  },
  {
    id: 'wpp-lf-f3-007',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'consultivo',
    title: 'Lista fria — perfil de busca',
    body: 'Oi, {{nome_lead}}. Se você ainda estiver buscando imóvel, me diga só uma coisa: seria para morar ou investir? Se não estiver, eu paro por aqui.',
  },
  {
    id: 'wpp-lf-f3-008',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'leve',
    title: 'Lista fria — sim ou não',
    body: '{{nome_lead}}, pode me responder só com “sim” ou “não”: faz sentido eu te mandar opções de imóveis neste momento?',
  },
  {
    id: 'wpp-lf-f3-009',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'direto',
    title: 'Lista fria — última tentativa objetiva',
    body: 'Olá, {{nome_lead}}. Última tentativa por aqui: você quer receber informações de imóveis ou prefere que eu remova seu contato desta abordagem?',
  },
  {
    id: 'wpp-lf-f3-010',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'terceira_mensagem',
    tone: 'reativacao',
    title: 'Lista fria — pausar ou seguir',
    body: '{{nome_lead}}, estou revisando minha base de contatos. Quer que eu siga te avisando sobre oportunidades imobiliárias ou prefere que eu pause definitivamente?',
  },
  {
    id: 'wpp-lf-f4-002',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'leve',
    title: 'Lista fria — encerramento com respeito',
    body: 'Oi, {{nome_lead}}. Como não tivemos retorno, vou pausar meu contato por aqui. Se em outro momento imóvel voltar ao seu radar, fico à disposição.',
  },
  {
    id: 'wpp-lf-f4-003',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Lista fria — porta aberta',
    body: '{{nome_lead}}, vou encerrar esta tentativa de contato para não ser inconveniente. Caso queira avaliar imóveis futuramente, pode me chamar por aqui.',
  },
  {
    id: 'wpp-lf-f4-004',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'executivo',
    title: 'Lista fria — encerramento profissional',
    body: 'Olá, {{nome_lead}}. Como não consegui confirmar seu interesse, vou finalizar este contato. Obrigado pela atenção e fico disponível se precisar de apoio imobiliário no futuro.',
  },
  {
    id: 'wpp-lf-f4-005',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'leve',
    title: 'Lista fria — sem insistência',
    body: '{{nome_lead}}, não vou insistir para não te incomodar. Vou pausar meus retornos por aqui. Se fizer sentido conversar em outro momento, estou à disposição.',
  },
  {
    id: 'wpp-lf-f4-006',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Lista fria — encerramento claro',
    body: 'Oi, {{nome_lead}}. Estou encerrando este contato porque não tive retorno. Se quiser receber opções de imóveis futuramente, é só me chamar.',
  },
  {
    id: 'wpp-lf-f4-007',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'direto',
    title: 'Lista fria — final objetivo',
    body: '{{nome_lead}}, vou retirar este contato da minha cadência de retorno. Caso queira falar sobre imóveis depois, sigo à disposição por aqui.',
  },
  {
    id: 'wpp-lf-f4-008',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'reativacao',
    title: 'Lista fria — reativação pausada',
    body: 'Olá, {{nome_lead}}. Como não consegui falar com você, vou deixar este contato pausado. Se imóvel voltar a ser prioridade, posso te ajudar com opções mais alinhadas.',
  },
  {
    id: 'wpp-lf-f4-009',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'leve',
    title: 'Lista fria — despedida leve',
    body: '{{nome_lead}}, obrigado pelo espaço. Vou parar meus contatos por aqui. Se algum dia fizer sentido ver imóveis novamente, pode me chamar sem compromisso.',
  },
  {
    id: 'wpp-lf-f4-010',
    channel: 'whatsapp',
    leadType: 'lista_fria',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Lista fria — fechamento elegante',
    body: 'Oi, {{nome_lead}}. Para respeitar seu tempo, vou encerrar esta abordagem. Fico à disposição se no futuro você quiser avaliar opções de imóveis com calma.',
  },
  {
    id: 'wpp-vp-f1-002',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — percepção da visita',
    body: 'Oi, {{nome_lead}}, tudo bem? Aqui é {{nome_corretor}}, da {{empresa}}. Depois da sua visita ao plantão do {{empreendimento}}, queria saber o que você achou e se ficou alguma dúvida.',
  },
  {
    id: 'wpp-vp-f1-003',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'direto',
    title: 'Visitou plantão — próxima etapa',
    body: '{{nome_lead}}, tudo bem? Passando para dar continuidade ao seu atendimento após a visita ao plantão. Faz sentido eu te mandar uma simulação ou revisar as unidades disponíveis?',
  },
  {
    id: 'wpp-vp-f1-004',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'executivo',
    title: 'Visitou plantão — retorno profissional',
    body: 'Olá, {{nome_lead}}. Sou {{nome_corretor}}, da {{empresa}}. Gostaria de dar sequência ao atendimento iniciado no plantão do {{empreendimento}} e entender se ficou algum ponto pendente para decisão.',
  },
  {
    id: 'wpp-vp-f1-005',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — dúvidas abertas',
    body: 'Oi, {{nome_lead}}. Depois da sua visita, queria entender se sua dúvida maior ficou em planta, valor, fluxo de pagamento ou disponibilidade. Assim eu te ajudo com mais precisão.',
  },
  {
    id: 'wpp-vp-f1-006',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'leve',
    title: 'Visitou plantão — conversa leve',
    body: '{{nome_lead}}, tudo bem? Queria saber como ficou sua impressão do {{empreendimento}} depois da visita. Alguma unidade ou planta chamou mais sua atenção?',
  },
  {
    id: 'wpp-vp-f1-007',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — atendimento continuado',
    body: 'Olá, {{nome_lead}}. Estou retomando seu atendimento do plantão para ver se posso te ajudar com disponibilidade atual, simulação ou comparação entre opções.',
  },
  {
    id: 'wpp-vp-f1-008',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'direto',
    title: 'Visitou plantão — simulação ajustada',
    body: '{{nome_lead}}, depois da sua visita, posso montar uma simulação mais ajustada ao seu perfil? Às vezes uma pequena mudança de unidade já altera bastante o fluxo.',
  },
  {
    id: 'wpp-vp-f1-009',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'urgencia_elegante',
    title: 'Visitou plantão — disponibilidade pós-visita',
    body: 'Oi, {{nome_lead}}. Estou acompanhando as unidades do {{empreendimento}} depois da sua visita. Quer que eu confira o que ainda está disponível dentro do perfil que você gostou?',
  },
  {
    id: 'wpp-vp-f1-010',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'primeira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — retomada com família',
    body: '{{nome_lead}}, tudo bem? Queria saber se você conseguiu conversar com calma depois da visita ao plantão e se posso te ajudar com algum ponto para avançarmos.',
  },
  {
    id: 'wpp-vp-f2-002',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'leve',
    title: 'Visitou plantão — retomada gentil',
    body: 'Oi, {{nome_lead}}. Só retomando meu contato depois da sua visita. Você conseguiu avaliar melhor o {{empreendimento}} ou prefere que eu te ajude com uma comparação mais objetiva?',
  },
  {
    id: 'wpp-vp-f2-003',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — objeção principal',
    body: '{{nome_lead}}, pensando na sua visita, qual ponto ficou mais importante para você decidir: valor, planta, localização, fluxo de pagamento ou disponibilidade?',
  },
  {
    id: 'wpp-vp-f2-004',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'direto',
    title: 'Visitou plantão — próxima conversa',
    body: 'Olá, {{nome_lead}}. Faz sentido marcarmos uma conversa rápida para eu revisar as opções que você viu no plantão e entender se alguma ainda se encaixa no seu momento?',
  },
  {
    id: 'wpp-vp-f2-005',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'urgencia_elegante',
    title: 'Visitou plantão — unidade desejada',
    body: '{{nome_lead}}, como você já conheceu o plantão, vale acompanharmos a disponibilidade com atenção. Quer que eu confira se ainda temos algo próximo do que você gostou?',
  },
  {
    id: 'wpp-vp-f2-006',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'executivo',
    title: 'Visitou plantão — retorno objetivo',
    body: 'Olá, {{nome_lead}}. Retomo para saber se deseja avançar com uma análise mais objetiva do {{empreendimento}}: disponibilidade, fluxo e cenário de pagamento.',
  },
  {
    id: 'wpp-vp-f2-007',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — simulação ou nova visita',
    body: 'Oi, {{nome_lead}}. Para te ajudar melhor: você prefere que eu monte uma simulação agora ou seria mais útil agendar uma nova visita com foco nas unidades que mais combinam com você?',
  },
  {
    id: 'wpp-vp-f2-008',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'leve',
    title: 'Visitou plantão — decisão em aberto',
    body: '{{nome_lead}}, fiquei com você em mente depois da visita. Ainda está avaliando o {{empreendimento}} ou acabou seguindo para outro caminho?',
  },
  {
    id: 'wpp-vp-f2-009',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — apoio na comparação',
    body: 'Olá, {{nome_lead}}. Se você estiver comparando com outros projetos, posso te ajudar a organizar os pontos principais para a decisão ficar mais clara.',
  },
  {
    id: 'wpp-vp-f2-010',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'segunda_mensagem',
    tone: 'direto',
    title: 'Visitou plantão — retorno rápido',
    body: '{{nome_lead}}, me diga só uma coisa: você quer seguir avaliando o {{empreendimento}} ou prefere que eu pause os retornos por enquanto?',
  },
  {
    id: 'wpp-vp-f3-002',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'direto',
    title: 'Visitou plantão — tentativa de avanço',
    body: '{{nome_lead}}, como você já conheceu o plantão, acho que vale uma última conversa objetiva: quer que eu veja a melhor opção disponível hoje dentro do seu perfil?',
  },
  {
    id: 'wpp-vp-f3-003',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'urgencia_elegante',
    title: 'Visitou plantão — janela de disponibilidade',
    body: 'Oi, {{nome_lead}}. Algumas disponibilidades podem mudar rápido depois da visita. Se ainda houver interesse, posso conferir uma alternativa boa antes de você decidir.',
  },
  {
    id: 'wpp-vp-f3-004',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — dúvida que trava',
    body: '{{nome_lead}}, geralmente depois da visita a decisão trava em algum ponto específico. No seu caso foi valor, planta, pagamento ou comparação com outro projeto?',
  },
  {
    id: 'wpp-vp-f3-005',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'executivo',
    title: 'Visitou plantão — análise final',
    body: 'Olá, {{nome_lead}}. Se desejar, faço uma análise final das opções do {{empreendimento}} para você decidir com clareza se vale avançar ou não.',
  },
  {
    id: 'wpp-vp-f3-006',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'leve',
    title: 'Visitou plantão — sem pressão',
    body: 'Oi, {{nome_lead}}. Sem pressão: você ainda quer que eu acompanhe as opções do {{empreendimento}} para você ou prefere deixar em pausa?',
  },
  {
    id: 'wpp-vp-f3-007',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'direto',
    title: 'Visitou plantão — simulação decisiva',
    body: '{{nome_lead}}, quer que eu monte uma simulação final para você comparar com calma? Se não fizer sentido, eu pauso seus retornos por aqui.',
  },
  {
    id: 'wpp-vp-f3-008',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — retomada por perfil',
    body: 'Olá, {{nome_lead}}. Posso buscar uma unidade mais alinhada ao que você comentou na visita. Talvez exista uma opção mais adequada do que a primeira que você viu.',
  },
  {
    id: 'wpp-vp-f3-009',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'urgencia_elegante',
    title: 'Visitou plantão — última checagem',
    body: '{{nome_lead}}, antes de eu pausar seu atendimento, quer que eu faça uma última checagem de disponibilidade e fluxo dentro do que conversamos no plantão?',
  },
  {
    id: 'wpp-vp-f3-010',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'terceira_mensagem',
    tone: 'consultivo',
    title: 'Visitou plantão — conversa de fechamento',
    body: 'Oi, {{nome_lead}}. Podemos fazer uma conversa rápida para entender se o {{empreendimento}} segue no seu radar ou se encerramos essa análise por enquanto?',
  },
  {
    id: 'wpp-vp-f4-002',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Visitou plantão — pausa pós-visita',
    body: '{{nome_lead}}, como não consegui retorno depois da sua visita, vou pausar meu acompanhamento por aqui. Se quiser retomar o {{empreendimento}}, fico à disposição.',
  },
  {
    id: 'wpp-vp-f4-003',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'leve',
    title: 'Visitou plantão — porta aberta',
    body: 'Oi, {{nome_lead}}. Vou deixar seu atendimento em aberto, sem insistir. Se quiser falar sobre valores, plantas ou disponibilidade depois, pode me chamar por aqui.',
  },
  {
    id: 'wpp-vp-f4-004',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'executivo',
    title: 'Visitou plantão — encerramento profissional',
    body: 'Olá, {{nome_lead}}. Como não tivemos continuidade após a visita, vou encerrar meus retornos. Permaneço à disposição se desejar reavaliar o {{empreendimento}} futuramente.',
  },
  {
    id: 'wpp-vp-f4-005',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Visitou plantão — sem insistência',
    body: '{{nome_lead}}, não quero insistir sem necessidade. Vou pausar o acompanhamento, mas sigo por aqui se quiser revisar alguma condição ou unidade.',
  },
  {
    id: 'wpp-vp-f4-006',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'direto',
    title: 'Visitou plantão — classificação final',
    body: 'Oi, {{nome_lead}}. Vou pausar seu atendimento por enquanto. Se o {{empreendimento}} ainda fizer sentido para você, me avise que retomo de forma objetiva.',
  },
  {
    id: 'wpp-vp-f4-007',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'leve',
    title: 'Visitou plantão — retorno futuro',
    body: '{{nome_lead}}, obrigado pela visita e pelo tempo. Vou deixar meu contato à disposição caso queira retomar a conversa em outro momento.',
  },
  {
    id: 'wpp-vp-f4-008',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Visitou plantão — encerramento com apoio',
    body: 'Olá, {{nome_lead}}. Como não avançamos depois da visita, vou pausar os retornos. Se precisar comparar opções ou rever uma simulação, posso te ajudar.',
  },
  {
    id: 'wpp-vp-f4-009',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'urgencia_elegante',
    title: 'Visitou plantão — disponibilidade futura',
    body: '{{nome_lead}}, vou pausar seu atendimento agora. Se quiser, em outro momento posso verificar novamente disponibilidade e condições atualizadas do {{empreendimento}}.',
  },
  {
    id: 'wpp-vp-f4-010',
    channel: 'whatsapp',
    leadType: 'visitou_plantao',
    phase: 'mensagem_final',
    tone: 'consultivo',
    title: 'Visitou plantão — fechamento elegante',
    body: 'Oi, {{nome_lead}}. Para respeitar seu tempo, vou encerrar meus retornos por aqui. Fico disponível se quiser continuar a análise do {{empreendimento}} no futuro.',
  },
]
