export const PME_CADENCE_SEEDS = [
  {
    id: 'cad-lista-fria-v1',
    leadType: 'lista_fria',
    title: 'Lista fria / comprada — cadência permission-based',
    status: 'seed',
    objective: 'Abrir conversa com baixo atrito, validar interesse e remover rapidamente quem não quer contato.',
    riskLevel: 'alto',
    recommendedMode: 'assistido',
    guardrails: [
      'Não presumir interesse atual do lead.',
      'Evitar tom de cobrança ou insistência agressiva.',
      'Dar saída clara para o lead encerrar o contato.',
      'Não seguir cadência após opt-out, rejeição clara ou número errado.',
    ],
    stopOnFeedbacks: [
      'nao_quer_contato',
      'sem_interesse',
      'numero_errado',
      'lead_ja_atendido',
      'opt_out',
    ],
    pauseOnFeedbacks: [
      'retornar_depois',
      'interessado',
      'enviar_informacoes',
    ],
    steps: [
      {
        order: 1,
        when: 'D0',
        channel: 'whatsapp',
        phase: 'primeira_mensagem',
        humanAction: true,
        title: 'Abertura leve com permissão',
        instruction: 'Enviar mensagem curta validando se imóvel ainda é assunto para o lead.',
        expectedResult: 'Lead responde se tem interesse, pede informações, solicita pausa ou ignora.',
      },
      {
        order: 2,
        when: 'D0 ou D1',
        channel: 'call',
        phase: 'primeira_mensagem',
        humanAction: true,
        title: 'Ligação de triagem',
        instruction: 'Ligar com script de permissão. Não vender produto antes de confirmar interesse.',
        expectedResult: 'Classificar interesse, retorno futuro, sem interesse, número errado ou envio de informações.',
      },
      {
        order: 3,
        when: 'D2',
        channel: 'whatsapp',
        phase: 'segunda_mensagem',
        humanAction: true,
        title: 'Segunda tentativa educada',
        instruction: 'Retomar com saída clara: posso enviar algo objetivo ou encerro o contato?',
        expectedResult: 'Lead sinaliza se quer ou não receber opções.',
      },
      {
        order: 4,
        when: 'D5',
        channel: 'whatsapp',
        phase: 'terceira_mensagem',
        humanAction: true,
        title: 'Último filtro comercial',
        instruction: 'Perguntar de forma objetiva se imóvel ainda faz sentido neste momento.',
        expectedResult: 'Resposta simples: sim, não, depois ou sem resposta.',
      },
      {
        order: 5,
        when: 'D8',
        channel: 'whatsapp',
        phase: 'mensagem_final',
        humanAction: true,
        title: 'Encerramento respeitoso',
        instruction: 'Pausar a cadência sem fechar a porta para contato futuro.',
        expectedResult: 'Lead encerrado como sem resposta ou reativável futuro.',
      },
    ],
  },
  {
    id: 'cad-visitou-plantao-v1',
    leadType: 'visitou_plantao',
    title: 'Visitou plantão — cadência pós-visita consultiva',
    status: 'seed',
    objective: 'Retomar a percepção da visita, descobrir objeção principal e avançar para simulação, nova visita ou encerramento claro.',
    riskLevel: 'medio',
    recommendedMode: 'assistido',
    guardrails: [
      'Nunca tratar como lista fria: este lead já teve experiência presencial.',
      'Retomar contexto da visita sempre que possível.',
      'Investigar objeção antes de oferecer nova unidade ou condição.',
      'Pausar se o lead pedir tempo ou retorno em data específica.',
    ],
    stopOnFeedbacks: [
      'agendou_visita',
      'quer_simulacao',
      'negociacao',
      'sem_interesse',
      'opt_out',
    ],
    pauseOnFeedbacks: [
      'retornar_depois',
      'em_comparacao',
      'falar_com_familia',
    ],
    steps: [
      {
        order: 1,
        when: 'D0',
        channel: 'whatsapp',
        phase: 'primeira_mensagem',
        humanAction: true,
        title: 'Retomada pós-visita',
        instruction: 'Perguntar percepção da visita e se ficou dúvida sobre planta, valor, fluxo ou disponibilidade.',
        expectedResult: 'Lead informa objeção, pede simulação, aceita nova conversa ou não responde.',
      },
      {
        order: 2,
        when: 'D0 ou D1',
        channel: 'call',
        phase: 'primeira_mensagem',
        humanAction: true,
        title: 'Ligação consultiva pós-plantão',
        instruction: 'Ligar para entender o que travou a decisão e propor próximo passo objetivo.',
        expectedResult: 'Simulação, nova visita, retorno futuro, comparação com outro projeto ou encerramento.',
      },
      {
        order: 3,
        when: 'D2',
        channel: 'whatsapp',
        phase: 'segunda_mensagem',
        humanAction: true,
        title: 'Objeção principal',
        instruction: 'Perguntar se o ponto principal é valor, planta, localização, fluxo ou comparação.',
        expectedResult: 'Lead revela o motivo da indecisão ou aceita ajuda com análise objetiva.',
      },
      {
        order: 4,
        when: 'D4 ou D5',
        channel: 'whatsapp',
        phase: 'terceira_mensagem',
        humanAction: true,
        title: 'Tentativa de avanço',
        instruction: 'Oferecer simulação final, checagem de disponibilidade ou nova visita focada.',
        expectedResult: 'Avanço para simulação/visita ou lead pausado.',
      },
      {
        order: 5,
        when: 'D7',
        channel: 'whatsapp',
        phase: 'mensagem_final',
        humanAction: true,
        title: 'Pausa elegante pós-visita',
        instruction: 'Pausar o acompanhamento sem parecer abandono nem cobrança.',
        expectedResult: 'Lead encerrado como sem resposta pós-visita ou reativável futuro.',
      },
    ],
  },
]

export function getCurrentOperationCadences() {
  return PME_CADENCE_SEEDS.filter((cadence) =>
    ['lista_fria', 'visitou_plantao'].includes(cadence.leadType),
  )
}

export function getCadenceByLeadType(leadType) {
  return PME_CADENCE_SEEDS.find((cadence) => cadence.leadType === leadType)
}
